// features/feed/mocks.ts
import type { Post, SentimentType, ComposerData } from "./types";

export const MOCK_POSTS: Post[] = [
  {
    id: "1",
    author: { name: "Alex Trader", handle: "@alextrader", avatar: "https://i.pravatar.cc/120?img=12", verified: true, isPremium: true, bio: "Professional swing trader | 8+ years experience | Sharing technical analysis & market insights" },
    timestamp: "2h ago",
    type: "signal",
    text: "Strong bullish pattern on $AAPL. Breaking resistance at $180. Perfect risk/reward setup for swing traders.",
    sentiment: "bullish",
    market: "stocks",
    price: "subscribers-only",
    ticker: "$AAPL",
    direction: "long",
    timeframe: "1d",
    risk: "medium",
    accuracy: 78,
    sampleSize: 125,
    entry: "$180",
    stopLoss: "$175",
    takeProfit: "$195",
    likes: 2340,
    comments: 145,
    reposts: 289,
    views: 12450,
    tags: ["#TechnicalAnalysis", "#Stocks", "#Signals"],
    isEditorPick: true
  },
  {
    id: "2",
    author: { name: "Crypto Whale", handle: "@cryptowhale", avatar: "https://i.pravatar.cc/120?img=33", verified: true, bio: "Early Bitcoin adopter | Crypto analyst since 2013 | Not financial advice" },
    timestamp: "4h ago",
    type: "analysis",
    text: "Bitcoin forming a perfect head and shoulders pattern. Watch for breakdown below $42k. This could trigger massive liquidations.",
    sentiment: "bearish",
    market: "crypto",
    price: "pay-per-post",
    ticker: "$BTC",
    likes: 1567,
    comments: 323,
    reposts: 534,
    views: 8456,
    tags: ["#Bitcoin", "#Crypto", "#TechnicalAnalysis"],
    isEditorPick: true
  },
  {
    id: "3",
    author: { name: "Algo Dev", handle: "@algodev", avatar: "https://i.pravatar.cc/120?img=25", verified: true, isPremium: true, bio: "Quantitative developer | Building algo trading systems | Python & ML enthusiast" },
    timestamp: "6h ago",
    type: "code",
    text: "New mean reversion strategy showing 65% win rate. Full implementation available for premium subscribers. Backtested on 3 years of data.",
    market: "crypto",
    price: "subscribers-only",
    language: "Python",
    codeSnippet: "def calculate_signals(df):\n    rsi = ta.rsi(df['close'], 14)\n    return rsi < 30",
    likes: 945,
    comments: 178,
    reposts: 256,
    views: 5234,
    tags: ["#AlgoTrading", "#Python", "#Code"],
    sentiment: "neutral"
  },
  {
    id: "4",
    author: { name: "Market News", handle: "@marketnews", avatar: "https://i.pravatar.cc/120?img=41", verified: true, bio: "Breaking market news & economic updates | Real-time coverage of global markets" },
    timestamp: "8h ago",
    type: "news",
    text: "Breaking: Fed announces interest rate decision. Market volatility expected across all sectors. FOMC statement released at 2 PM EST.",
    sentiment: "neutral",
    market: "stocks",
    price: "free",
    likes: 2789,
    comments: 634,
    reposts: 1145,
    views: 15678,
    tags: ["#Fed", "#MarketNews", "#Economy"]
  },
  {
    id: "5",
    author: { name: "Tech Analyst", handle: "@techanalyst", avatar: "https://i.pravatar.cc/120?img=55", verified: true, bio: "Technical analysis expert | Chart patterns & indicators | 10k+ followers" },
    timestamp: "10h ago",
    type: "signal",
    text: "Bearish signal on $TSLA. Support breaking at $200. Consider shorting with tight stops.",
    sentiment: "bearish",
    market: "stocks",
    price: "free",
    ticker: "$TSLA",
    direction: "short",
    timeframe: "4h",
    risk: "high",
    accuracy: 68,
    sampleSize: 45,
    entry: "$200",
    stopLoss: "$210",
    takeProfit: "$180",
    likes: 1123,
    comments: 89,
    reposts: 178,
    views: 6789,
    tags: ["#TSLA", "#Signals"]
  },
  {
    id: "6",
    author: {
      name: "Premium Analyst",
      handle: "@premiumanalyst",
      avatar: "https://i.pravatar.cc/120?img=68",
      verified: true,
      isPremium: true,
      subscriptionPrice: 29
    },
    timestamp: "5h ago",
    type: "signal",
    text: "Exclusive trading signal: Major breakout pattern detected on $NVDA. This is a premium analysis with detailed entry points, stop loss, and multiple take profit levels.",
    sentiment: "bullish",
    market: "stocks",
    price: "pay-per-post",
    accessLevel: "paid",
    postPrice: 9,
    isPurchased: false,
    isSubscriber: false,
    ticker: "$NVDA",
    direction: "long",
    timeframe: "1d",
    risk: "low",
    accuracy: 85,
    sampleSize: 200,
    entry: "$500",
    stopLoss: "$485",
    takeProfit: "$540",
    likes: 3456,
    comments: 234,
    reposts: 567,
    views: 18900,
    tags: ["#NVDA", "#PremiumSignal", "#TechStocks"],
    isEditorPick: true
  },
  {
    id: "7",
    author: {
      name: "Crypto Pro",
      handle: "@cryptopro",
      avatar: "https://i.pravatar.cc/120?img=72",
      verified: true,
      subscriptionPrice: 29
    },
    timestamp: "3h ago",
    type: "education",
    text: "📚 Exclusive tutorial for my subscribers: Advanced DeFi strategies that helped me achieve 200% returns in 2024. Including smart contract analysis and yield farming optimization.",
    market: "crypto",
    price: "subscribers-only",
    accessLevel: "subscribers",
    isPurchased: false,
    isSubscriber: false,
    likes: 2134,
    comments: 156,
    reposts: 445,
    views: 9876,
    tags: ["#DeFi", "#Education", "#CryptoStrategy"]
  },
  {
    id: "8",
    author: {
      name: "Elite Trader",
      handle: "@elitetrader",
      avatar: "https://i.pravatar.cc/120?img=45",
      verified: true,
      isPremium: true,
      subscriptionPrice: 49
    },
    timestamp: "1h ago",
    type: "analysis",
    text: "🔥 PREMIUM ONLY: My private hedge fund strategy revealed. Institutional-grade market analysis with proprietary indicators. This content is exclusively for premium tier subscribers.",
    sentiment: "bullish",
    market: "stocks",
    price: "subscribers-only",
    accessLevel: "premium",
    isPurchased: false,
    isSubscriber: false,
    likes: 5678,
    comments: 423,
    reposts: 892,
    views: 25600,
    tags: ["#Premium", "#InstitutionalTrading", "#MarketAnalysis"],
    isEditorPick: true
  },
  {
    id: "9",
    author: {
      name: "Day Trader Max",
      handle: "@daytradermax",
      avatar: "https://i.pravatar.cc/120?img=38",
      verified: true,
      subscriptionPrice: 29
    },
    timestamp: "30m ago",
    type: "signal",
    text: "🎯 Scalping setup on $SPY - My highest conviction trade this week. Full breakdown with entry, multiple targets, and risk management included.",
    sentiment: "bullish",
    market: "stocks",
    price: "pay-per-post",
    accessLevel: "paid",
    postPrice: 9,
    isPurchased: false,
    isSubscriber: false,
    ticker: "$SPY",
    direction: "long",
    timeframe: "15m",
    risk: "medium",
    accuracy: 72,
    sampleSize: 150,
    entry: "$450",
    stopLoss: "$448",
    takeProfit: "$455",
    likes: 1890,
    comments: 145,
    reposts: 289,
    views: 8234,
    tags: ["#Scalping", "#SPY", "#DayTrading"]
  }
];

export const TRENDING_TICKERS = [
  { ticker: "$AAPL", change: "+2.4%", sentiment: "bullish" as SentimentType, mentions: "1.2K" },
  { ticker: "$TSLA", change: "-1.2%", sentiment: "bearish" as SentimentType, mentions: "987" },
  { ticker: "$BTC", change: "+5.6%", sentiment: "bullish" as SentimentType, mentions: "2.3K" },
  { ticker: "$ETH", change: "+3.8%", sentiment: "bullish" as SentimentType, mentions: "1.6K" },
  { ticker: "$NVDA", change: "+4.2%", sentiment: "bullish" as SentimentType, mentions: "890" }
];

export const TOP_AUTHORS = [
  { name: "Alex Trader", handle: "@alextrader", avatar: "https://i.pravatar.cc/120?img=12", followers: "45.2K", isFollowing: false },
  { name: "Crypto Whale", handle: "@cryptowhale", avatar: "https://i.pravatar.cc/120?img=33", followers: "38.5K", isFollowing: true },
  { name: "Algo Dev", handle: "@algodev", avatar: "https://i.pravatar.cc/120?img=25", followers: "32.1K", isFollowing: false }
];

export const INITIAL_COMPOSER_STATE: ComposerData = {
  text: "",
  teaser: "",
  sentiment: null,
  isPaid: false,
  isCode: false,
  ticker: "",
  direction: "",
  timeframe: "1h",
  risk: "medium",
  entry: "",
  stopLoss: "",
  takeProfit: "",
  language: "Python",
  codeDescription: "",
  codeSnippet: "",
  compatibility: "",
  accessType: "free",
  price: "",
  verifiedOnly: false,
  visibility: "all",
  scheduledDate: "",
  scheduledTime: "",
  expiryDays: "",
  commentsEnabled: true
};
