-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtc5esIYaceqZQpwD
NWoD0E5QffmWVFZNeXBokLnKls6gCgYIKoZIzj0DAQehRANCAASXLgpOVSQmIX28
H7b11dcjxzTzgDkPvfZrL8jiTzBWoq3dPHVRVjsAECpBAJSd3V9lR3+XeEXqeXA/
k3J5jMVx
-----END PRIVATE KEY-----