name: Deploy to Railway

on:
  push:
    branches:
      - nova-hub
      - main
    paths:
      - 'custom-backend/**'
      - '.github/workflows/deploy-railway.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway link ${{ secrets.RAILWAY_PROJECT_ID }}
          railway up --service custom-backend --detach

      - name: Deployment Status
        run: echo "✅ Backend deployed to Railway successfully!"
